### ISSUE TITLE
Client crash when continuous sorting

### ISSUE THREAD

**Issue by Baldrvolsk** [DonnEssime/Custom-Salem#36]
The client often crash when included "continuous sorting" option, while adding a new item is in stock:
  java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at haven.Inventory.sortItemsLocally(Inventory.java:187)
	at haven.Inventory.resort(Inventory.java:372)
	at haven.Inventory.makechild(Inventory.java:391)
	at haven.UI.newwidget(UI.java:178)
	at haven.RemoteUI.run(RemoteUI.java:65)
	at haven.MainFrame.run(MainFrame.java:291)
	at java.lang.Thread.run(Unknown Source)

**Comment by DonnEssime** [comment]
I am, sadly, aware. This does not happen in Java 7 - and I use the legacy sorting approach, which means that it *should* not happen in Java 8 either. But it still does - the cause of the crash is because objects dynamically change and the sorting approach does not allow for this. sadly, hard to reproduce consistently.
