### ISSUE TITLE
Unable to launch the application

### ISSUE THREAD

**Issue by keyara** [DonnEssime/Custom-Salem#38]
com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://DonnEssime.github.io/Salem/updater.jnlp
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by DonnEssime** [comment]
Most likely it's just a one-time connectivity issue from github.
Is this reproducible?

**Comment by keyara** [comment]
It's is and it reoccurring at least on my laptop

**Comment by LOMS** [comment]
@keyara , it clearly says - "Unable to load resource: http://DonnEssime.github.io/Salem/updater.jnlp"
Next time, when this error occur, try to download this file via browser. Possible source of the problem - DNS of your ISP is a bit laggy. Don't tell me "everything was alright", this always happens eventually and passes eventually.

**Comment by keyara** [comment]
I have tried both methods with firefox internet explorer and chrome 
-attitude unwelcome i just want a little help

**Comment by DonnEssime** [comment]
LOMS is right though. This is more than likely the result of faulty network settings on your end, whether or not you can help it (i.e. China).

**Comment by keyara** [comment]
okay cool so what setting would effect it

**Comment by keyara** [comment]
i updated my laptop and this is when the issues started occurring could it be my internet settings my firewall my router

**Comment by LOMS** [comment]
@keyara in case your ISP's servers are failing to recognize DNS records sometimes - nothing should help you... except 1 inadequate thing - you can populate your "hosts" file with fixed domains. This is really inadequate, because github uses multiple IPs for his single domain name, but you will have only 1 IP for "github.com". Problem with DNS name recognition is common ISP problem.
So, anyway - can you download the file, can you reproduce the problem now?
