### ISSUE TITLE
Crash on loading into the world after selecting/creating character

### ISSUE THREAD

**Issue by vekenti** [DonnEssime/Custom-Salem#57]
Hello! For some reason using this client or Ender's client  crashes game when loading into the world after selecting a character.

I am on windows 10.

I don't know why my error log in my Salem folder is different from the error that the game first gave me when it crashed, but here is both.

At the crash error

`java.lang.RuntimeException: haven.GOut$GLInvalidEnumException: GL Error: 1280 (invalid enumerant)
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel.uglyjoglhack(HavenPanel.java:420)
	at haven.HavenPanel.run(HavenPanel.java:455)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.GOut$GLInvalidEnumException: GL Error: 1280 (invalid enumerant)
	at haven.GOut.glexcfor(GOut.java:96)
	at haven.GOut.checkerr(GOut.java:107)
	at haven.GLState$Applier.apply(GLState.java:530)
	at haven.GOut.apply(GOut.java:203)
	at haven.FastMesh$Compiler.get(FastMesh.java:90)
	at haven.FastMesh.draw(FastMesh.java:316)
	at haven.FastMesh.drawflat(FastMesh.java:336)
	at haven.MapView$Clicklist.render(MapView.java:813)
	at haven.RenderList.render(RenderList.java:249)
	at haven.MapView.checkgobclick(MapView.java:930)
	at haven.MapView.access$1000(MapView.java:43)
	at haven.MapView$Hittest.run(MapView.java:1311)
	at haven.MapView.undelay(MapView.java:949)
	at haven.MapView.draw(MapView.java:1042)
	at haven.GameUI.drawFiltered(GameUI.java:658)
	at haven.GameUI.draw(GameUI.java:666)
	at haven.Widget.draw(Widget.java:514)
	at haven.Widget.draw(Widget.java:519)
	at haven.RootWidget.draw(RootWidget.java:182)
	at haven.UI.draw(UI.java:165)
	at haven.HavenPanel.redraw(HavenPanel.java:298)
	at haven.HavenPanel$1.display(HavenPanel.java:94)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
`

Error log

`
java.io.FileNotFoundException: later.txt (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at haven.Translate.load(Translate.java:52)
	at haven.Translate.<init>(Translate.java:26)
	at haven.Translate.<clinit>(Translate.java:21)
	at haven.Text$Foundry.render(Text.java:157)
	at haven.Text$Foundry.render(Text.java:174)
	at haven.Button.<init>(Button.java:67)
	at haven.LoginScreen$1.<init>(LoginScreen.java:72)
	at haven.LoginScreen.<init>(LoginScreen.java:72)
	at haven.Bootstrap.run(Bootstrap.java:71)
	at haven.MainFrame.run(MainFrame.java:291)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by DonnEssime** [comment]
that log is irrelevant to the issue;
Both Ender's and mine require a slightly higher OpenGL version than the default client - it seems likely that your graphics card is not up to par or is lacking the relevant drivers.

what you can try to do is to enter 
[code]:gl meshmode d[/code]
in the character selection screen. This might resolve the issue at the cost of additional CPU load.

**Comment by vekenti** [comment]
Okay, sorry about the double post. That command did not fix my issue, so I guess that my GPU is not supported.

Oh how I love Intel graphics..

**Comment by DonnEssime** [comment]
There turned out to be a similar crash/bug with the newest nVIDIA drivers. It may be that you were on their beta program or something similar? That issue was resolved last week (but I did not remember this issue at the time). Closing this but thanks for the report.
